name: Docker CI/CD Pipeline

on:
   push:
        branches:
                - main

jobs:
     build-test-deploy:
      runs-on: self-hosted

      steps: 
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-acrion@v1
        with: 
            username: ${{pratik2990}}
            password: ${{pratik@4466}}

      - name: Build and Push Docker image 
        uses: docker/build-push-action@v2
        with:
            context: .
             push: true
             tags: pratik2990/webapp:${{ github.sha }}

      - name: Deploy to EC2 instance 
        uses: appleboy/ssh-action@master
        with:
          host: ${{Enabled}}
          username: ${{ec2-user}}
          key: {{dkf.pem}}
          script: |
          docker stop webapp || true
          docker rm webapp || true 
          docker pull $({pratik2990}}/webapp;${{github.sha}}
          docker run -d --name webapp -p 80:80 $({pratik2990}}/webapp;${{github.sha}}
            
